
package foo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PaymentIFBinding", targetNamespace = "urn:Foo", wsdlLocation = "https://sep.shaparak.ir/payments/referencepayment.asmx?WSDL")
public class PaymentIFBinding
    extends Service
{

    private final static URL PAYMENTIFBINDING_WSDL_LOCATION;
    private final static WebServiceException PAYMENTIFBINDING_EXCEPTION;
    private final static QName PAYMENTIFBINDING_QNAME = new QName("urn:Foo", "PaymentIFBinding");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
//            url = new URL("file:/home/omidp/NetBeansProjects/WebApplication1/src/conf/xml-resources/web-services/NewWebServiceFromWSDL/wsdl/referencepayment.asmx.wsdl");
            url = new URL("https://sep.shaparak.ir/payments/referencepayment.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYMENTIFBINDING_WSDL_LOCATION = url;
        PAYMENTIFBINDING_EXCEPTION = e;
    }

    public PaymentIFBinding() {
        super(__getWsdlLocation(), PAYMENTIFBINDING_QNAME);
    }

    public PaymentIFBinding(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYMENTIFBINDING_QNAME, features);
    }

    public PaymentIFBinding(URL wsdlLocation) {
        super(wsdlLocation, PAYMENTIFBINDING_QNAME);
    }

    public PaymentIFBinding(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYMENTIFBINDING_QNAME, features);
    }

    public PaymentIFBinding(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentIFBinding(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaymentIFBindingSoap
     */
    @WebEndpoint(name = "PaymentIFBindingSoap")
    public PaymentIFBindingSoap getPaymentIFBindingSoap() {
        return super.getPort(new QName("urn:Foo", "PaymentIFBindingSoap"), PaymentIFBindingSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentIFBindingSoap
     */
    @WebEndpoint(name = "PaymentIFBindingSoap")
    public PaymentIFBindingSoap getPaymentIFBindingSoap(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Foo", "PaymentIFBindingSoap"), PaymentIFBindingSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns PaymentIFBindingSoap
     */
    @WebEndpoint(name = "PaymentIFBindingSoap12")
    public PaymentIFBindingSoap getPaymentIFBindingSoap12() {
        return super.getPort(new QName("urn:Foo", "PaymentIFBindingSoap12"), PaymentIFBindingSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentIFBindingSoap
     */
    @WebEndpoint(name = "PaymentIFBindingSoap12")
    public PaymentIFBindingSoap getPaymentIFBindingSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Foo", "PaymentIFBindingSoap12"), PaymentIFBindingSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYMENTIFBINDING_EXCEPTION!= null) {
            throw PAYMENTIFBINDING_EXCEPTION;
        }
        return PAYMENTIFBINDING_WSDL_LOCATION;
    }

}
