
package foo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PaymentIFBindingSoap", targetNamespace = "urn:Foo")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface PaymentIFBindingSoap {


    /**
     * 
     * @param string1
     * @param string2
     * @return
     *     returns double
     */
    @WebMethod(action = "verifyTransaction")
    @WebResult(name = "result", partName = "result")
    public double verifyTransaction(
        @WebParam(name = "String_1", partName = "String_1")
        String string1,
        @WebParam(name = "String_2", partName = "String_2")
        String string2);

    /**
     * 
     * @param string1
     * @param string2
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public double verifyTransaction1(
        @WebParam(name = "String_1", partName = "String_1")
        String string1,
        @WebParam(name = "String_2", partName = "String_2")
        String string2);

    /**
     * 
     * @param password
     * @param string1
     * @param string2
     * @param username
     * @return
     *     returns double
     */
    @WebMethod(action = "reverseTransaction")
    @WebResult(name = "result", partName = "result")
    public double reverseTransaction(
        @WebParam(name = "String_1", partName = "String_1")
        String string1,
        @WebParam(name = "String_2", partName = "String_2")
        String string2,
        @WebParam(name = "Username", partName = "Username")
        String username,
        @WebParam(name = "Password", partName = "Password")
        String password);

    /**
     * 
     * @param password
     * @param amount
     * @param string1
     * @param string2
     * @return
     *     returns double
     */
    @WebMethod(action = "reverseTransaction1")
    @WebResult(name = "result", partName = "result")
    public double reverseTransaction1(
        @WebParam(name = "String_1", partName = "String_1")
        String string1,
        @WebParam(name = "String_2", partName = "String_2")
        String string2,
        @WebParam(name = "Password", partName = "Password")
        String password,
        @WebParam(name = "Amount", partName = "Amount")
        double amount);

}
